// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export type {
    DirectoryListing,
    DiscourseInfo,
    DocumentStats,
    FileContentPayload,
    FileItem,
    FunctionalInfo,
    LexicalAnalysisResult,
    MorphologyInfo,
    PhonologyInfo,
    PoeticSuggestionsResult,
    PoeticWordItem,
    PolysemyInfo,
    PragmaticsInfo,
    SimilarityResult,
    SuggestionItem,
    SynonymGroup,
    WordSenseItem
} from "./models.js";
