// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as discourse$0 from "../../../gown/discourse/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as expansion$0 from "../../../gown/expansion/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as functional$0 from "../../../gown/functional/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pragmatics$0 from "../../../gown/pragmatics/models.js";

/**
 * DirectoryListing contains files in the current directory.
 */
export interface DirectoryListing {
    "currentDir": string;
    "dirName": string;
    "files": FileItem[] | null;
}

/**
 * DiscourseInfo captures thematic progression and coherence across sentences.
 */
export interface DiscourseInfo {
    "thematicProgression": discourse$0.ThematicProgressionStep[] | null;
}

/**
 * DocumentStats reports live statistical measurements of document content.
 */
export interface DocumentStats {
    "characters": number;
    "charactersNoSpaces": number;
    "words": number;
    "sentences": number;
    "paragraphs": number;
    "readingTimeMinutes": number;
    "speakingTimeMinutes": number;
    "uniqueWords": number;
    "vocabularyRichness": number;
}

/**
 * FileContentPayload represents the retrieved content of a file.
 */
export interface FileContentPayload {
    "name": string;
    "path": string;
    "extension": string;
    "content": string;
    "size": number;
}

/**
 * FileItem represents a discovered file in the current directory.
 */
export interface FileItem {
    "name": string;
    "path": string;
    "extension": string;
    "size": number;
    "modTime": number;
}

/**
 * FunctionalInfo captures systemic functional linguistics (Theme/Rheme, Mood, Cohesion).
 */
export interface FunctionalInfo {
    "themeRheme": functional$0.ThemeRheme;
    "interpersonal": functional$0.InterpersonalAnalysis;
    "cohesiveTies": functional$0.CohesiveTie[] | null;
}

/**
 * LexFileInfo describes a WordNet Lexicographer File domain with word count.
 */
export interface LexFileInfo {
    "name": string;
    "wordCount": number;
}

/**
 * LexFileWordItem represents an individual word entry belonging to a LexFile.
 */
export interface LexFileWordItem {
    "word": string;
    "pos": string;
    "definition": string;
    "synsetId": string;
    "examples"?: string[] | null;
    "lexfile"?: string;
}

/**
 * LexicalAnalysisResult bundles all lexical, semantic, and morphological analysis.
 */
export interface LexicalAnalysisResult {
    "requestId": number;
    "word": string;
    "found": boolean;
    "primaryLemma": string;
    "senses": WordSenseItem[] | null;
    "recommendedSenseIndex": number;
    "wsdConfidence": number;
    "synonymGroups": SynonymGroup[] | null;
    "antonyms": string[] | null;
    "hypernyms": string[] | null;
    "hyponyms": string[] | null;
    "meronyms": string[] | null;
    "morphology": MorphologyInfo;
    "phonology": PhonologyInfo;
    "polysemy": PolysemyInfo;
    "poetics": PoeticSuggestionsResult;
    "hierarchyTree": string;
    "expansionTree"?: expansion$0.Node | null;
    "functional": FunctionalInfo;
    "pragmatics": PragmaticsInfo;
    "discourse": DiscourseInfo;
}

/**
 * MorphologyInfo summarizes morphological variations and lemma resolution.
 */
export interface MorphologyInfo {
    "original": string;
    "lemmas": string[] | null;
    "posList": string[] | null;
    "inflectedVariations": string[] | null;
}

/**
 * PhonologyInfo provides syllable breakdown and metrics.
 */
export interface PhonologyInfo {
    "syllableCount": number;
    "syllables": string[] | null;
    "cvPattern": string;
}

/**
 * PoeticSuggestionsResult bundles rhymes, alliterations, and CV rhythm matches for creative writing.
 */
export interface PoeticSuggestionsResult {
    "word": string;
    "rhymeEnding": string;
    "onsetCluster": string;
    "syllableCount": number;
    "cvPattern": string;
    "rhymes": PoeticWordItem[] | null;
    "alliterations": PoeticWordItem[] | null;
    "cvSimilar": PoeticWordItem[] | null;
}

/**
 * PoeticWordItem represents a word recommendation matching rhyming, alliteration, or rhythmic criteria.
 */
export interface PoeticWordItem {
    "word": string;
    "pos": string;
    "syllableCount": number;
    "cvPattern": string;
    "rhymeScore": number;
    "gloss": string;
}

/**
 * PolysemyInfo quantifies lexical ambiguity.
 */
export interface PolysemyInfo {
    "totalSenses": number;
    "isPolysemous": boolean;
    "entropy": number;
}

/**
 * PragmaticsInfo captures speech acts, politeness, and indexical deixis.
 */
export interface PragmaticsInfo {
    "speechAct": pragmatics$0.IllocutionaryForce;
    "politeness": pragmatics$0.PolitenessAnalysis;
    "deixis": pragmatics$0.DeicticExpression[] | null;
}

/**
 * SimilarityResult reports semantic proximity between two words.
 */
export interface SimilarityResult {
    "word1": string;
    "word2": string;
    "score": number;
    "metric": string;
    "error"?: string;
}

/**
 * SuggestionItem represents a single autocomplete recommendation.
 */
export interface SuggestionItem {
    "word": string;
    "lemma": string;
    "pos": string;
    "gloss": string;
    "senseNumber": number;
    "source"?: string;
}

/**
 * SynonymGroup groups synonyms belonging to a specific word sense.
 */
export interface SynonymGroup {
    "senseNumber": number;
    "senseDefinition": string;
    "pos": string;
    "words": string[] | null;
}

/**
 * WordGraphEdge represents a semantic relation connecting two nodes.
 */
export interface WordGraphEdge {
    "source": string;
    "target": string;

    /**
     * "synonym", "hypernym", "hyponym", "antonym", "meronym", "similar", "same_lexfile"
     */
    "label": string;
    "type": string;
    "weight"?: number;
}

/**
 * WordGraphNode represents a node in the document word network.
 */
export interface WordGraphNode {
    "id": string;
    "label": string;

    /**
     * "word", "intermediate", "synset"
     */
    "type": string;
    "pos"?: string;
    "count"?: number;
    "is_document_word": boolean;
    "definition"?: string;
    "depth"?: number;
}

/**
 * WordGraphResult holds nodes and edges for the document word graph.
 */
export interface WordGraphResult {
    "nodes": WordGraphNode[] | null;
    "edges": WordGraphEdge[] | null;
}

/**
 * WordSenseItem represents a single lexical sense for the active word.
 */
export interface WordSenseItem {
    "id": string;
    "senseNumber": number;
    "pos": string;
    "definition": string;
    "examples": string[] | null;
    "lemma": string;
    "lexfile": string;
    "ili": string;
    "confidence": number;
    "isSelected": boolean;
}
