// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProgressionType categorizes Daneš's thematic progression patterns.
 */
export enum ProgressionType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * T1 -> T1 (same theme maintained)
     */
    ProgressionConstant = "constant_theme",

    /**
     * R1 -> T2 (rheme becomes next theme)
     */
    ProgressionLinear = "linear_progression",

    /**
     * Theme changes completely
     */
    ProgressionNew = "new_theme",
};

/**
 * ThematicProgressionStep represents the transition between two consecutive clause themes.
 */
export interface ThematicProgressionStep {
    "sentence_id": number;
    "theme": string;
    "rheme": string;
    "type": ProgressionType;
}
