// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CohesionType classifies the lexical relation connecting two text words.
 */
export enum CohesionType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CohesionRepetition = "repetition",
    CohesionSynonymy = "synonymy",
    CohesionHypernymy = "hypernymy",
    CohesionHyponymy = "hyponymy",
    CohesionMeronymy = "meronymy",
    CohesionAntonymy = "antonymy",
};

/**
 * CohesiveTie represents a cohesive link between two words in a discourse.
 */
export interface CohesiveTie {
    "word1": string;
    "word2": string;
    "type": CohesionType;
}

/**
 * InterpersonalAnalysis holds interpersonal meaning attributes.
 */
export interface InterpersonalAnalysis {
    "mood": MoodType;
    "polarity": Polarity;
    "modality": ModalityKind;
    "speech_function": SpeechFunction;
}

/**
 * ModalityKind classifies modal stance.
 */
export enum ModalityKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * e.g. maybe, probably, must
     */
    ModalityProbability = "probability",

    /**
     * e.g. usually, sometimes, always
     */
    ModalityUsuality = "usuality",

    /**
     * e.g. should, must, ought to
     */
    ModalityObligation = "obligation",

    /**
     * e.g. willing, want, intend
     */
    ModalityInclination = "inclination",
    ModalityNone = "none",
};

/**
 * MoodType classifies interpersonal grammatical mood.
 */
export enum MoodType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    MoodDeclarative = "declarative",
    MoodInterrogative = "interrogative",
    MoodImperative = "imperative",
    MoodExclamative = "exclamative",
};

/**
 * Polarity indicates positive or negative grammatical polarity.
 */
export enum Polarity {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PolarityPositive = "positive",
    PolarityNegative = "negative",
};

/**
 * SpeechFunction classifies the communicative act.
 */
export enum SpeechFunction {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SpeechStatement = "statement",
    SpeechQuestion = "question",
    SpeechCommand = "command",
    SpeechOffer = "offer",
};

/**
 * ThemeRheme represents the information structure of a clause in SFL.
 */
export interface ThemeRheme {
    "clause": string;
    "theme": string;
    "rheme": string;
}
