// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileService provides local filesystem operations for text and markdown documents.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../pkg/models/models.js";

/**
 * GetWorkingDir returns the current working directory path.
 */
export function GetWorkingDir(): $CancellablePromise<string> {
    return $Call.ByID(3265971228);
}

/**
 * ListFiles lists .txt and .md files in the specified directory.
 * If dirPath is empty, returns an empty listing (default state).
 */
export function ListFiles(dirPath: string): $CancellablePromise<models$0.DirectoryListing | null> {
    return $Call.ByID(2157397385, dirPath);
}

/**
 * ReadFile reads the content of a .txt or .md file from the specified path.
 */
export function ReadFile(filePath: string): $CancellablePromise<models$0.FileContentPayload | null> {
    return $Call.ByID(1417640724, filePath);
}

/**
 * WriteFile writes the given content to a file at filePath.
 */
export function WriteFile(filePath: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(3997906131, filePath, content);
}
