// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as FileService from "./fileservice.js";
import * as LexicalService from "./lexicalservice.js";
export {
    FileService,
    LexicalService
};
