// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LexicalService provides WordNet lexical lookups, autocomplete suggestions, and semantic calculations.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../pkg/models/models.js";

/**
 * AnalyzeDocument computes realtime statistical measurements for the editor status bar.
 */
export function AnalyzeDocument(text: string): $CancellablePromise<models$0.DocumentStats> {
    return $Call.ByID(774512167, text);
}

/**
 * AnalyzeWord performs morphological, sense, contextual disambiguation, and relationship analysis.
 */
export function AnalyzeWord(word: string, sentenceContext: string, requestId: number): $CancellablePromise<models$0.LexicalAnalysisResult> {
    return $Call.ByID(210490654, word, sentenceContext, requestId);
}

/**
 * CalculateSimilarity measures Wu-Palmer similarity between two concepts.
 */
export function CalculateSimilarity(word1: string, word2: string): $CancellablePromise<models$0.SimilarityResult> {
    return $Call.ByID(1137991401, word1, word2);
}

/**
 * GetPoeticSuggestions analyzes rhyming ending, alliterative onset, and Consonant-Vowel (CV) meter.
 */
export function GetPoeticSuggestions(word: string): $CancellablePromise<models$0.PoeticSuggestionsResult> {
    return $Call.ByID(2109872559, word);
}

/**
 * GetSuggestions returns rich vocabulary completion candidates including exact, prefix, synonym, and contextual matches.
 */
export function GetSuggestions(query: string, limit: number): $CancellablePromise<models$0.SuggestionItem[] | null> {
    return $Call.ByID(3036513803, query, limit);
}

/**
 * IsReady checks if the lexical resource has completed initialization.
 */
export function IsReady(): $CancellablePromise<boolean> {
    return $Call.ByID(3193888781);
}
