// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as LexicalService from "./lexicalservice.js";
export {
    LexicalService
};

export type {
    DiscourseInfo,
    DocumentStats,
    FunctionalInfo,
    LexicalAnalysisResult,
    MorphologyInfo,
    PhonologyInfo,
    PoeticSuggestionsResult,
    PoeticWordItem,
    PolysemyInfo,
    PragmaticsInfo,
    SimilarityResult,
    SuggestionItem,
    SynonymGroup,
    WordSenseItem
} from "./models.js";
