// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LexicalService provides WordNet lexical lookups, autocomplete suggestions, and semantic calculations.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AnalyzeDocument computes realtime statistical measurements for the editor status bar.
 */
export function AnalyzeDocument(text: string): $CancellablePromise<$models.DocumentStats> {
    return $Call.ByID(2551376170, text);
}

/**
 * AnalyzeWord performs morphological, sense, contextual disambiguation, and relationship analysis.
 */
export function AnalyzeWord(word: string, sentenceContext: string, requestId: number): $CancellablePromise<$models.LexicalAnalysisResult> {
    return $Call.ByID(3561670195, word, sentenceContext, requestId);
}

/**
 * CalculateSimilarity measures Wu-Palmer similarity between two concepts.
 */
export function CalculateSimilarity(word1: string, word2: string): $CancellablePromise<$models.SimilarityResult> {
    return $Call.ByID(4077285812, word1, word2);
}

/**
 * GetPoeticSuggestions analyzes rhyming ending, alliterative onset, and Consonant-Vowel (CV) meter.
 */
export function GetPoeticSuggestions(word: string): $CancellablePromise<$models.PoeticSuggestionsResult> {
    return $Call.ByID(3855753996, word);
}

/**
 * GetSuggestions returns rich vocabulary completion candidates including:
 * 1. Exact lemma match and prefix matches from WordNet Trie
 * 2. Lemmas containing the query as a substring
 * 3. Synonyms if the query is a word
 * 4. Words whose definitions contain the query (or words from query's definitions)
 * 5. Words whose examples contain the query (or words from query's examples)
 */
export function GetSuggestions(query: string, limit: number): $CancellablePromise<$models.SuggestionItem[] | null> {
    return $Call.ByID(1446473016, query, limit);
}

/**
 * IsReady checks if the lexical resource has completed initialization.
 */
export function IsReady(): $CancellablePromise<boolean> {
    return $Call.ByID(1642651448);
}
