// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as discourse$0 from "../gown/discourse/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as expansion$0 from "../gown/expansion/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as functional$0 from "../gown/functional/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pragmatics$0 from "../gown/pragmatics/models.js";

/**
 * DiscourseInfo captures thematic progression and coherence across sentences.
 */
export interface DiscourseInfo {
    "thematicProgression": discourse$0.ThematicProgressionStep[] | null;
}

/**
 * DocumentStats reports live statistical measurements of document content.
 */
export interface DocumentStats {
    "characters": number;
    "charactersNoSpaces": number;
    "words": number;
    "sentences": number;
    "paragraphs": number;
    "readingTimeMinutes": number;
    "speakingTimeMinutes": number;
    "uniqueWords": number;
    "vocabularyRichness": number;
}

/**
 * FunctionalInfo captures systemic functional linguistics (Theme/Rheme, Mood, Cohesion).
 */
export interface FunctionalInfo {
    "themeRheme": functional$0.ThemeRheme;
    "interpersonal": functional$0.InterpersonalAnalysis;
    "cohesiveTies": functional$0.CohesiveTie[] | null;
}

/**
 * LexicalAnalysisResult bundles all lexical, semantic, and morphological analysis.
 */
export interface LexicalAnalysisResult {
    "requestId": number;
    "word": string;
    "found": boolean;
    "primaryLemma": string;
    "senses": WordSenseItem[] | null;
    "recommendedSenseIndex": number;
    "wsdConfidence": number;
    "synonymGroups": SynonymGroup[] | null;
    "antonyms": string[] | null;
    "hypernyms": string[] | null;
    "hyponyms": string[] | null;
    "meronyms": string[] | null;
    "morphology": MorphologyInfo;
    "phonology": PhonologyInfo;
    "polysemy": PolysemyInfo;
    "poetics": PoeticSuggestionsResult;
    "hierarchyTree": string;
    "expansionTree"?: expansion$0.Node | null;
    "functional": FunctionalInfo;
    "pragmatics": PragmaticsInfo;
    "discourse": DiscourseInfo;
}

/**
 * MorphologyInfo summarizes morphological variations and lemma resolution.
 */
export interface MorphologyInfo {
    "original": string;
    "lemmas": string[] | null;
    "posList": string[] | null;
    "inflectedVariations": string[] | null;
}

/**
 * PhonologyInfo provides syllable breakdown and metrics.
 */
export interface PhonologyInfo {
    "syllableCount": number;
    "syllables": string[] | null;
    "cvPattern": string;
}

/**
 * PoeticSuggestionsResult bundles rhymes, alliterations, and CV rhythm matches for creative writing.
 */
export interface PoeticSuggestionsResult {
    "word": string;
    "rhymeEnding": string;
    "onsetCluster": string;
    "syllableCount": number;
    "cvPattern": string;
    "rhymes": PoeticWordItem[] | null;
    "alliterations": PoeticWordItem[] | null;
    "cvSimilar": PoeticWordItem[] | null;
}

/**
 * PoeticWordItem represents a word recommendation matching rhyming, alliteration, or rhythmic criteria.
 */
export interface PoeticWordItem {
    "word": string;
    "pos": string;
    "syllableCount": number;
    "cvPattern": string;
    "rhymeScore": number;
    "gloss": string;
}

/**
 * PolysemyInfo quantifies lexical ambiguity.
 */
export interface PolysemyInfo {
    "totalSenses": number;
    "isPolysemous": boolean;
    "entropy": number;
}

/**
 * PragmaticsInfo captures speech acts, politeness, and indexical deixis.
 */
export interface PragmaticsInfo {
    "speechAct": pragmatics$0.IllocutionaryForce;
    "politeness": pragmatics$0.PolitenessAnalysis;
    "deixis": pragmatics$0.DeicticExpression[] | null;
}

/**
 * SimilarityResult reports semantic proximity between two words.
 */
export interface SimilarityResult {
    "word1": string;
    "word2": string;
    "score": number;
    "metric": string;
    "error"?: string;
}

/**
 * SuggestionItem represents a single autocomplete recommendation.
 */
export interface SuggestionItem {
    "word": string;
    "lemma": string;
    "pos": string;
    "gloss": string;
    "senseNumber": number;
    "source"?: string;
}

/**
 * SynonymGroup groups synonyms belonging to a specific word sense.
 */
export interface SynonymGroup {
    "senseNumber": number;
    "senseDefinition": string;
    "pos": string;
    "words": string[] | null;
}

/**
 * WordSenseItem represents a single lexical sense for the active word.
 */
export interface WordSenseItem {
    "id": string;
    "senseNumber": number;
    "pos": string;
    "definition": string;
    "examples": string[] | null;
    "lemma": string;
    "lexfile": string;
    "ili": string;
    "confidence": number;
    "isSelected": boolean;
}
