// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Node represents a vertex in an expansion tree.
 */
export interface Node {
    "id": string;
    "word": string;
    "type": NodeType;
    "pos"?: string;
    "definition"?: string;
    "relation"?: string;
    "depth": number;
    "score": number;
    "children"?: (Node | null)[] | null;
}

/**
 * NodeType identifies the entity represented by an expansion node.
 */
export enum NodeType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    NodeWord = "word",
    NodeSynset = "synset",
    NodeDefinition = "definition",
    NodeToken = "token",
};
