// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    DeixisType,
    PolitenessStrategy,
    SpeechActClass
} from "./models.js";

export type {
    DeicticExpression,
    IllocutionaryForce,
    PolitenessAnalysis
} from "./models.js";
