// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DeicticExpression represents an identified deictic item in text.
 */
export interface DeicticExpression {
    "word": string;
    "type": DeixisType;

    /**
     * "proximal", "distal", "speaker", "addressee"
     */
    "proximity"?: string;
    "resolved_to"?: string;
}

/**
 * DeixisType categorizes the deictic reference dimension.
 */
export enum DeixisType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DeixisPerson = "person",
    DeixisSpatial = "spatial",
    DeixisTemporal = "temporal",
    DeixisDiscourse = "discourse",
};

/**
 * IllocutionaryForce characterizes the pragmatic intent of an utterance.
 */
export interface IllocutionaryForce {
    "class": SpeechActClass;
    "performative_verb"?: string;
    "confidence": number;
}

/**
 * PolitenessAnalysis evaluates an utterance for interpersonal politeness features.
 */
export interface PolitenessAnalysis {
    "strategy": PolitenessStrategy;
    "hedge_score": number;
    "mitigation_tags": string[] | null;
}

/**
 * PolitenessStrategy indicates the face-management strategy employed.
 */
export enum PolitenessStrategy {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * claiming common ground, compliments
     */
    StrategyPositivePoliteness = "positive_politeness",

    /**
     * hedging, minimizing imposition, indirectness
     */
    StrategyNegativePoliteness = "negative_politeness",

    /**
     * direct, unmitigated imperative
     */
    StrategyBaldOnRecord = "bald_on_record",

    /**
     * indirect hints, ambiguous
     */
    StrategyOffRecord = "off_record",
};

/**
 * SpeechActClass represents Searle's classification of illocutionary acts.
 */
export enum SpeechActClass {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * Commits speaker to the truth (claim, state, report)
     */
    ActAssertive = "assertive",

    /**
     * Attempts to get addressee to act (ask, order, request)
     */
    ActDirective = "directive",

    /**
     * Commits speaker to future action (promise, offer, vow)
     */
    ActCommissive = "commissive",

    /**
     * Expresses psychological state (thank, apologize, welcome)
     */
    ActExpressive = "expressive",

    /**
     * Alters the institutional state (declare, resign, baptize)
     */
    ActDeclaration = "declaration",
};
